### ISSUE TITLE
Launcher throws exception when given a 301

### ISSUE THREAD

**Issue by skwerlman** [TechnicPack/LauncherV3#126]
When getting the solder endpoint `/api/modpack/`, the launcher throws a JSON parsing error when it receives a 301 Redirect from the server.

My server is redirecting from `http://solder.tetrarch.co/api/modpack/` to `https://solder.tetrarch.co/api/modpack/`.

```
[B#347] net.technicpack.rest.RestfulAPIException: Error parsing response JSON at URL [http://solder.tetrarch.co/api/modpack/]
[B#347]     at net.technicpack.rest.RestObject.getRestObject(RestObject.java:155)
[B#347]     at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#347]     at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#347]     at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#347]     at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#347]     at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#347]     at net.technicpack.launchercore.modpacks.PackLoadJob$5.run(PackLoadJob.java:180)
[B#347]     at java.lang.Thread.run(Unknown Source)
[B#347] Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[B#347]     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:810)
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:775)
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:724)
[B#347]     at com.google.gson.Gson.fromJson(Gson.java:696)
[B#347]     at net.technicpack.rest.RestObject.getRestObject(RestObject.java:139)
[B#347]     ... 7 more
[B#347] Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[B#347]     at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
[B#347]     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
[B#347]     ... 12 more
```

**Comment by Lord-Ptolemy** [comment]
Will confirm if this is still an issue and if so attempt a fix.

**Comment by Pyker** [comment]
Considering that the HTTPS URL returns a 502, there's no way to test this.

**Comment by Lord-Ptolemy** [comment]
Will be trying to reproduce on my own Solder.
