### ISSUE TITLE
Can't play modpacks that are offline

### ISSUE THREAD

**Issue by Pyker** [TechnicPack/LauncherV3#233]
Unsure if it's related to the log4j fix or if it's a general problem, but if a modpack is showing up as "Offline" and you attempt to play it, the launch procedure will fail (and hang, unabortable), with an exception related to libraries:

```
[B#709] java.lang.RuntimeException: Library org.apache.logging.log4j:log4j-api:2.0-beta9 not found.
[B#709] 	at net.technicpack.minecraftcore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:361)
[B#709] 	at net.technicpack.minecraftcore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:147)
[B#709] 	at net.technicpack.minecraftcore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:82)
[B#709] 	at net.technicpack.launcher.launch.Installer$1.run(Installer.java:174)
[B#709] 	at java.lang.Thread.run(Unknown Source)
```

**Comment by Pyker** [comment]
Upon further analysis, this is because the build steps aren't triggered when the modpack is marked as "local only".
