### ISSUE TITLE
HTTP 401 for URL: https://api.technicpack.net/modpack/...?build=0 when building running latest Launcher from source

### ISSUE THREAD

**Issue by vorburger** [TechnicPack/LauncherV3#243]
After fixing #193 with #242 unblocked the Microsoft Login, I still wasn't able to use it.

When I launch class `LauncherMain` from within an IDE (Eclipse), or `mvn package && `java -jar target/launcher-4.0-0.jar`, it's failing:

```
[B#0] Analytics Response [runLauncher]: 200
[B#0] net.technicpack.rest.RestfulAPIException: Error accessing URL [https://api.technicpack.net/modpack/hexxit?build=0]
[B#0] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:77)
[B#0] 	at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfo(HttpPlatformApi.java:50)
[B#0] 	at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfoForBulk(HttpPlatformApi.java:44)
[B#0] 	at net.technicpack.platform.cache.ModpackCachePlatformApi.pullAndCache(ModpackCachePlatformApi.java:132)
[B#0] 	at net.technicpack.platform.cache.ModpackCachePlatformApi.getPlatformPackInfo(ModpackCachePlatformApi.java:96)
[B#0] 	at net.technicpack.launcher.ui.components.modpacks.ModpackSelector$7.run(ModpackSelector.java:330)
[B#0] Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.technicpack.net/modpack/hexxit?build=0
[B#0] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
[B#0] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[B#0] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[B#0] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:56)
[B#0] 	... 5 more
[B#0] Starting download of https://www.gravatar.com/avatar/777da0eed8908835b1e9e08204f5beb2?s=60&d=retro, with 3 tries remaining
[B#0] Starting download of http://cdn.technicpack.net/platform2/pack-icons/552552.png?1443082685, with 3 tries remaining
[B#0] Starting download of http://cdn.technicpack.net/platform2/pack-icons/552552.png?1443082685, with 3 tries remaining
[B#0] Starting download of https://www.gravatar.com/avatar/f46511cf7e25a447592d34f140b38faa?s=60&d=retro, with 3 tries remaining
[B#0] Starting download of https://cdn.technicpack.net/platform2/pack-logos/1268231.png?1639358033, with 3 tries remaining
[B#0] Starting download of https://cdn.technicpack.net/platform2/pack-backgrounds/1268231.jpg?1639358033, with 3 tries remaining
[B#0] Starting download of https://www.gravatar.com/avatar/886822449a26aa16096316b85887a35c?s=60&d=retro, with 3 tries remaining
[B#0] net.technicpack.rest.RestfulAPIException: Error accessing URL [https://api.technicpack.net/modpack/pokecentral-pixelmon?build=0]
[B#0] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:77)
[B#0] 	at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfo(HttpPlatformApi.java:50)
[B#0] 	at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfoForBulk(HttpPlatformApi.java:44)
[B#0] 	at net.technicpack.platform.cache.ModpackCachePlatformApi.pullAndCache(ModpackCachePlatformApi.java:132)
[B#0] 	at net.technicpack.platform.cache.ModpackCachePlatformApi.getPlatformPackInfo(ModpackCachePlatformApi.java:96)
[B#0] 	at net.technicpack.launcher.ui.components.modpacks.ModpackSelector$7.run(ModpackSelector.java:330)
[B#0] Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.technicpack.net/modpack/pokecentral-pixelmon?build=0
[B#0] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
[B#0] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[B#0] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[B#0] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:56)
[B#0] 	... 5 more
[B#0] Starting download of https://cdn.technicpack.net/platform2/pack-icons/1268231.png?1639358033, with 3 tries remaining
[B#0] java.lang.RuntimeException: Library org.apache.logging.log4j:log4j-api:2.15.0 not found.
[B#0] 	at net.technicpack.minecraftcore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:361)
[B#0] 	at net.technicpack.minecraftcore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:147)
[B#0] 	at net.technicpack.minecraftcore.launch.MinecraftLauncher.la
```

**Comment by vorburger** [comment]
BTW just FYI I was wondering if perhaps the `master` branch wasn't the currently actively developed one of this project, so I've tried out the [`feature/cleanup`](https://github.com/TechnicPack/LauncherV3/tree/feature/cleanup) branch, but that doesn't have the Microsoft Login, and was last updated 2 years ago, so it looks like `master` is the correct branch. Perhaps that old `feature/cleanup` branch could be delete from this repo to avoid any future confusion?

@Pyker do you know what's causing these HTTP 401 errors?

**Comment by Pyker** [comment]
This is not a bug.

**Comment by Pyker** [comment]
It's a safety measure to prevent outdated versions of the launcher from running. You'll want to set the build number to something like 800

**Comment by Pyker** [comment]
For reference, this is what the arguments look like in my IDE: `-buildNumber 999 -launcheronly`, with the following as JVM options: `-Djava.net.preferIPv4Stack=true -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true`
