### ISSUE TITLE
Cannot launch Modpacks with Forge 47.2.0+ on Minecraft 1.20.1 

### ISSUE THREAD

**Issue by Fabl0s** [TechnicPack/LauncherV3#351]
Modpacks that contain the recent builds of Forge for 1.20.1 (possible other Versions too) refuse to launch with the Log Message below:

```
[B#822]  Missing: G:\Technic Launcher\cache\net\minecraftforge\forge\1.20.1-47.2.20\forge-1.20.1-47.2.20-client.jar
[B#822]  Some extra libraries are missing! Running the installer to generate them now.
[B#822]  JVM info: Microsoft - 17.0.8 - 17.0.8+7-LTS
[B#822]  java.net.preferIPv4Stack=true
[B#822]  Exception in thread "main" java.lang.reflect.InvocationTargetException
[B#822]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#822]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[B#822]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[B#822]  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[B#822]  	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:51)
[B#822]  Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.installer.actions.PostProcessors.process(java.io.File, java.io.File, java.io.File, java.io.File)'
[B#822]  	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1$ClientInstall4MultiMC.run(InstallerV1.java:35)
[B#822]  	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1.runClientInstall(InstallerV1.java:20)
[B#822]  	at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:26)
[B#822]  	... 5 more
[B#822] Process exited with code 1
```

Java Version doesnt seem to change anything, testend with Oracle Java 8 and MS JDK 17 and 21 in Launcher Options.
After some testing, Forge 47.2.0 seems to be the latest working Forge version, any Version after shows this behavior.

**Comment by Pyker** [comment]
This has been resolved by https://github.com/TechnicPack/LauncherV3/commit/12110348ee1341aa9f157981f1b7d4fa3c709672 and will be in the launcher starting with build 823.
